### ISSUE TITLE
缺少必要包

### ISSUE THREAD

**Issue by xbxdds** [Zi-YuanYang/CO3Net#1]
没有requirements.txt，令可否提供论文链接？感激不尽！

**Comment by Zi-YuanYang** [comment]
谢谢，我们把该文件上传了，请再查看一下。论文的early access版应该这几天会出来，请稍等一下下

> 没有requirements.txt，令可否提供论文链接？感激不尽！

**Comment by Zi-YuanYang** [comment]
> 没有requirements.txt，令可否提供论文链接？感激不尽！

论文可以在https://ieeexplore.ieee.org/document/10124928 下载
