### ISSUE TITLE
dataset download?

### ISSUE THREAD

**Issue by aa12356jm** [Zi-YuanYang/CO3Net#2]
hello ,thanks for your code and paper, can you share the dateset ? thanks agin,  624848668@qq.com

**Comment by Zi-YuanYang** [comment]
I'm sorry that I have no right to share these datasets. However, they are very easy to apply. PolyU needs to segment the ROIs at first, but I remember that Tongji, Multi-Spec and CASIA contain the segmented ROI images. Maybe you can apply them in official, you'll get a response in a few days. (Related websites you can found in our paper)

**Comment by Zi-YuanYang** [comment]
> hello ,thanks for your code and paper, can you share the dateset ? thanks agin, [624848668@qq.com](mailto:624848668@qq.com)

I'm sorry that I have no right to share these datasets. However, they are very easy to apply. PolyU needs to segment the ROIs at first, but I remember that Tongji, Multi-Spec and CASIA contain the segmented ROI images. Maybe you can apply them in official, you'll get a response in a few days. (Related websites you can found in our paper)

**Comment by aa12356jm** [comment]
> 
thanks ,i will try in official

**Comment by aa12356jm** [comment]
Is it convenient to leave your email address? thanks

**Comment by Zi-YuanYang** [comment]
> Is it convenient to leave your email address? thanks

Please feel free to contact me, if you have any question about our code or paper. My email is cziyuanyang@gmail.com.
